### ISSUE TITLE
cloning repo fails with file not found error

### ISSUE THREAD

**Issue by wakatana** [rhyolight/nupic.examples#5]
I was checking out this repository and got this error:

└──> git clone https://github.com/rhyolight/nupic.examples/tree/master/sine-prediction
Cloning into 'sine-prediction'...
p11-kit: invalid config filename, will be ignored in the future: /etc/pkcs11/modules/gnome-keyring-module
error: The requested URL returned error: 403 while accessing https://github.com/rhyolight/nupic.examples/tree/master/sine-prediction/info/refs
fatal: HTTP request failed

**Comment by rhyolight** [comment]
You have to clone the root directory, not a folder within the repo. 

    git clone https://github.com/rhyolight/nupic.examples.git
